<a href="https://colab.research.google.com/github/Prince6306238634/FP/blob/master/Matrix_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Program3
#Matrix ops

import numpy as np
M1 = np.array([[5, -10, 15], [3, -6, 9], [-4, 8, 12]])
print(M1)

M2 = np.array([[9, -18, 27], [11, 22, 33], [13, -26, 39]])
print(M2)
M3 = M1 + M2
print("Addition:")
print(M3)

print("Subtraction:")
print(M1 - M2)

print("Multiplication")
print(M1.dot(M2))

print("Transpose:")
print(M1.transpose())

print("Division")
print(np.divide(M1,M2))

[[  5 -10  15]
 [  3  -6   9]
 [ -4   8  12]]
[[  9 -18  27]
 [ 11  22  33]
 [ 13 -26  39]]
Addition:
[[ 14 -28  42]
 [ 14  16  42]
 [  9 -18  51]]
Subtraction:
[[ -4   8 -12]
 [ -8 -28 -24]
 [-17  34 -27]]
Multiplication
[[ 130 -700  390]
 [  78 -420  234]
 [ 208  -64  624]]
Transpose:
[[  5   3  -4]
 [-10  -6   8]
 [ 15   9  12]]
Division
[[ 0.55555556  0.55555556  0.55555556]
 [ 0.27272727 -0.27272727  0.27272727]
 [-0.30769231 -0.30769231  0.30769231]]


In [ ]:

print("Enter order of 1st matrix:")
m,n = list(map(int,input().split()))

print("Enter Row wise values")

# empty list for 1st matrix
mat1 = []

# row wise insertion in the matrix
for i in range(m) :
    print("Enter row",i,"value:")

    # take 1d- integer array input in one line
    row = list(map(int,input().split()))
    mat1.append(row)

print("Enter order of 2nd matrix:")

# take integer inputs in one line
p,q = list(map(int,input().split()))

print("Enter Row wise values")
# empty list for 2nd matrix
mat2 = []

# row wise insertion in the matrix
for j in range(p) :
    print("Enter row",j,"value:")

    # take 1d- integer array input in one line
    row = list(map(int,input().split()))
    mat2.append(row)

# showing 1st and 2nd matrix
print("Matrix 1:",mat1)
print("Matrix 2:",mat2)

# empty list for resulatant matrix
resultant = []

# create a 0-matrix of order m x q
for i in range(m):
    row = []
    for j in range(q):
        row.append(0)
        resultant.append(row)

print("Matrix Multiplication: ")

# perform matrix multiplication
# using nested for loops
for i in range(m):
    for j in range(q):
        for k in range(n) :
            resultant[i][j]=(mat1[i][k] * mat2[k][j])

# matrix printing row wise
for row in resultant:
    print(row)

Enter order of 1st matrix:
2 2
Enter Row wise values
Enter row 0 value:
1 2
Enter row 1 value:
2 3
Enter order of 2nd matrix:
2 2
Enter Row wise values
Enter row 0 value:
1 2
Enter row 1 value:
2 3
Matrix 1: [[1, 2], [2, 3]]
Matrix 2: [[1, 2], [2, 3]]
Matrix Multiplication: 
[6, 9]
[6, 9]
[0, 0]
[0, 0]
